sudo: false
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
script:
  - if [[ "$(git log --format=%s -n 1 $TRAVIS_COMMIT)" != *"[skip-ci]"* ]]; then
      STATICS='--src-statics node_modules/sinnerschrader-website-static/statics' npm run build
    else
      if [[ "$(git log --format=%s -n 1 $TRAVIS_COMMIT)" == *"[skip-ci]"* ]]; then
        echo "Commit subject ends with \"[skip-ci]\", skipping."
        exit 0
      fi
    fi
after_success:
  - npm run deploy-staging
  - npm run deploy
